# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 兰意
tagline: 安心的家，从兰意开始
background: {
  home: '文艺02.jpg',
  contact: '简约02.jpg',
  product: '简约03.jpg',
  about: '复古01.jpg',
  join: '复古03.jpg',
  credential: '简约01.jpg',
  jobsite: '复古04.jpg',
  workflow: '文艺01.jpg',
  sample: '简约04.jpg',
  workvideo: '复古02.jpg'
}
header_pages : ['product.md', 'about.md', 'join.md', 'credential.md', 'contact.md']
contact: {
  email: '33097987@qq.com',
  telephone: '0335-5979009'
}
email: 
description: > # this means to ignore newlines until "baseurl:"
  兰意就是一点心意
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
weixin_username: xhw33097987

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
